const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Plugins.InstantGamesBridge,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Behaviors.EightDir,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.InstantGamesBridge.Acts.AppendStorageDataGetRequest,
		C3.Plugins.InstantGamesBridge.Acts.SendStorageDataGetRequest,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.InstantGamesBridge.Acts.SendMessage,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.InstantGamesBridge.Acts.AppendStorageDataSetRequest,
		C3.Plugins.InstantGamesBridge.Acts.SendStorageDataSetRequest,
		C3.Plugins.InstantGamesBridge.Cnds.OnStorageDataSetRequestCompleted,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.InstantGamesBridge.Exps.StorageData,
		C3.Plugins.InstantGamesBridge.Cnds.OnStorageDataGetRequestCompleted,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.InstantGamesBridge.Cnds.HasStorageData,
		C3.Plugins.InstantGamesBridge.Cnds.IsStorageAvailable,
		C3.Plugins.System.Cnds.IsNaN,
		C3.Plugins.InstantGamesBridge.Cnds.IsStorageSupported,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.InstantGamesBridge.Acts.ShowRewarded,
		C3.Plugins.InstantGamesBridge.Acts.ShowBanner,
		C3.Plugins.InstantGamesBridge.Acts.AddToFavorites,
		C3.Plugins.InstantGamesBridge.Acts.InviteFriends,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedClosed,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedRewarded,
		C3.Plugins.InstantGamesBridge.Acts.ShowInterstitial
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Timer: 0},
	{player: 0},
	{Touch: 0},
	{Bullet: 0},
	{Num: 0},
	{Block: 0},
	{txtBlock: 0},
	{txtScore: 0},
	{Wall: 0},
	{TiledBackground: 0},
	{Sine: 0},
	{bg: 0},
	{Solid: 0},
	{rocket: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{Anchor: 0},
	{life: 0},
	{HP_TEXT: 0},
	{InstantGamesBridge: 0},
	{hill: 0},
	{Audio: 0},
	{menubutton: 0},
	{record: 0},
	{Sprite2: 0},
	{rew: 0},
	{Sprite3: 0},
	{boat: 0},
	{Bullet2: 0},
	{Browser: 0},
	{ship_kolvo: 0},
	{boat_bt: 0},
	{water: 0},
	{Sprite4: 0},
	{Text: 0},
	{bonustext: 0},
	{life2: 0},
	{boat_bt2: 0},
	{LocalStorage: 0},
	{rew2: 0},
	{Sprite5: 0},
	{"8Direction": 0},
	{FBlock: 0},
	{bullets: 0},
	{StartX: 0},
	{GameOver: 0},
	{Score: 0},
	{HP: 0},
	{ships: 0},
	{vNum: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	txtBlock: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	bg: class extends self.ISpriteInstance {},
	rocket: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	life: class extends self.ISpriteInstance {},
	HP_TEXT: class extends self.ITextInstance {},
	InstantGamesBridge: class extends self.IInstance {},
	hill: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	menubutton: class extends self.ISpriteInstance {},
	record: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	rew: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	boat: class extends self.ISpriteInstance {},
	Bullet2: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	ship_kolvo: class extends self.ITextInstance {},
	boat_bt: class extends self.ISpriteInstance {},
	water: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	bonustext: class extends self.ITextInstance {},
	life2: class extends self.ISpriteInstance {},
	boat_bt2: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	rew2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	FBlock: class extends self.ISpriteInstance {},
	bullets: class extends self.ISpriteInstance {}
}